package com.dtv.oss.domain;

import java.sql.Timestamp;

import com.dtv.oss.dto.QueryDTO;

public interface Query extends javax.ejb.EJBLocalObject {
  public void setStatus(String status);
  public String getStatus();
  public void setCreateOperatorId(int createOperatorId);
  public int getCreateOperatorId();
  public void setCreateTime(Timestamp createTime);
  public Timestamp getCreateTime();
  public void setScheduleType(String scheduleType);
  public String getScheduleType();
  public void setScheduleTime(Timestamp scheduleTime);
  public Timestamp getScheduleTime();
  public void setPerformTime(Timestamp performTime);
  public Timestamp getPerformTime();
  public void setQueryType(String queryType);
  public String getQueryType();
  public void setCustStatusList(String custStatusList);
  public String getCustStatusList();
  public void setCustTypeList(String custTypeList);
  public String getCustTypeList();
  public void setCustCreateTime1(Timestamp custCreateTime1);
  public Timestamp getCustCreateTime1();
  public void setCustCreateTime2(Timestamp custCreateTime2);
  public Timestamp getCustCreateTime2();
  public void setCustOpenSourceTypeList(String custOpenSourceTypeList);
  public String getCustOpenSourceTypeList();
  public void setCustOpenSourceIdList(String custOpenSourceIdList);
  public String getCustOpenSourceIdList();
  public void setCustName(String custName);
  public String getCustName();
  public void setCustAddress(String custAddress);
  public String getCustAddress();
  public void setCustDistrictIdList(String custDistrictIdList);
  public String getCustDistrictIdList();
  public void setAccountStatusList(String accountStatusList);
  public String getAccountStatusList();
  public void setAccountTypeList(String accountTypeList);
  public String getAccountTypeList();
  public void setAccountMopIdList(String accountMopIdList);
  public String getAccountMopIdList();
  public void setAccountAddress(String accountAddress);
  public String getAccountAddress();
  public void setAccountCreateTime1(Timestamp accountCreateTime1);
  public Timestamp getAccountCreateTime1();
  public void setAccountCreateTime2(Timestamp accountCreateTime2);
  public Timestamp getAccountCreateTime2();
  public void setCpStatusList(String cpStatusList);
  public String getCpStatusList();
  public void setCpProductIdList(String cpProductIdList);
  public String getCpProductIdList();
  public void setCpCreateTime1(Timestamp cpCreateTime1);
  public Timestamp getCpCreateTime1();
  public void setCpCreateTime2(Timestamp cpCreateTime2);
  public Timestamp getCpCreateTime2();
  public void setCpCampaignIdList(String cpCampaignIdList);
  public String getCpCampaignIdList();
  public void setDtCreate(Timestamp dtCreate);
  public Timestamp getDtCreate();
  public void setDtLastmod(Timestamp dtLastmod);
  public Timestamp getDtLastmod();
  public Integer getQueryId();
  public void setQueryName(String queryName);
  public String getQueryName();
  public void setQueryDesc(String queryDesc);
  public String getQueryDesc();
  public   double getAccountCashBalance1();
  public   double getAccountCashBalance2(); 
  public   double getAccountTokenBalance1();
  public   double getAccountTokenBalance2(); 
  public  java.sql.Timestamp getCpCampaignEndTime1();
  public java.sql.Timestamp getCpCampaignEndTime2(); 
  public java.sql.Timestamp getCpCampaignStartTime1();
  public java.sql.Timestamp getCpCampaignStartTime2(); 
  public java.lang.String getAccountDistrictIdList(); 
  public int getCustCurrentPoints1(); 
  public int getCustCurrentPoints2(); 
  public int getCustTotalPoints1(); 
  public int getCustTotalPoints2(); 
  public int getCustomerId(); 
  public void setAccountCashBalance1(double accountCashBalance1);
  public void setAccountCashBalance2(double accountCashBalance2); 
  public void setAccountTokenBalance1(double accountTokenBalance1);
  public void setAccountTokenBalance2(double accountTokenBalance2); 
  public void setCpCampaignEndTime1(java.sql.Timestamp cpCampaignEndTime1);
  public void setCpCampaignEndTime2(java.sql.Timestamp cpCampaignEndTime2);
  public void setCpCampaignStartTime1(java.sql.Timestamp cpCampaignStartTime1);
  public void setCpCampaignStartTime2(java.sql.Timestamp cpCampaignStartTime2);
  public void setAccountDistrictIdList(String accountDistrictIdList); 
  public void setCustCurrentPoints1(int custCurrentPoints1); 
  public void setCustCurrentPoints2(int custCurrentPoints2);
  public void setCustTotalPoints1(int custTotalPoints1);  
  public void setCustTotalPoints2(int custTotalPoints2); 
  public void setCustomerId(int customerId); 
  
  public   java.sql.Timestamp getAccountInvoiceCreateTime1(); 
  public   java.sql.Timestamp getAccountInvoiceCreateTime2(); 
  public   String getAccountInvoiceStatusList(); 
  public   void setAccountInvoiceCreateTime1(java.sql.Timestamp accountInvoiceCreateTime1); 
  public   void setAccountInvoiceCreateTime2(java.sql.Timestamp accountInvoiceCreateTime2); 
  public   void setAccountInvoiceStatusList(String accountInvoiceStatusList); 
  public   void setProductClassList(java.lang.String productClassList);
  public   void setBankAccountStatusList(java.lang.String bankAccountStatusList);
  public   java.lang.String getProductClassList();
  public   java.lang.String getBankAccountStatusList(); 
  public void setTemplateFlag(String templateFlag);
  public   java.lang.String getTemplateFlag();  
  public int ejbUpdate(QueryDTO dto);
}